apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: hireverse/notification-server
          env:
            - name: MAIL_ID
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: MAIL_ID
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: MAIL_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: notification-srv
spec:
  selector:
    app: notification
  ports:
    - name: notification
      protocol: TCP
      port: 6001
      targetPort: 6001