apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-depl
  namespace: hireverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: hireverse/notification-server
          env:
            - name: MAIL_ID
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: MAIL_ID
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: MAIL_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: DATABASE_URL
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: JWT_SECRET_KEY
          envFrom:
            - configMapRef:
                name: common-config

---
apiVersion: v1
kind: Service
metadata:
  name: notification-srv
  namespace: hireverse
spec:
  selector:
    app: notification
  ports:
    - name: express
      protocol: TCP
      port: 5002
      targetPort: 5002
    - name: grpc
      protocol: TCP
      port: 6002
      targetPort: 6002
    - name: websocket
      protocol: TCP
      port: 7002
      targetPort: 7002